"""Agentic KPIs computed in code (tac-7 had an agent write them).

Size up, Attempts down, Streak up, Presence down. Plus cost and gate pass rate.
Source of truth: agent/kpis.jsonl (one row per ADW run, upserted). agent/agentic_kpis.md is rendered.
"""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel

from .data_types import utcnow
from .state import ADWState
from .utils import agent_dir

STREAK_MAX_ATTEMPTS = 2
ATTEMPT_WORKFLOWS = {"adw_plan_iso", "adw_patch_iso"}


class KPIRow(BaseModel):
    adw_id: str
    date: str
    domain: str
    issue_number: str = ""
    issue_class: str = ""
    attempts: int = 1
    plan_size: int = 0
    added: int = 0
    removed: int = 0
    files: int = 0
    cost_usd: float = 0.0
    gates_passed: int = 0
    gates_total: int = 0
    shipped: bool = False
    created: str = ""
    updated: str = ""


def _rows_path() -> Path:
    return agent_dir() / "kpis.jsonl"


def load_rows() -> list[KPIRow]:
    path = _rows_path()
    if not path.exists():
        return []
    return [KPIRow.model_validate_json(line) for line in path.read_text().splitlines() if line.strip()]


def row_from_state(state: ADWState, diff: dict[str, int], plan_size: int, shipped: bool = False) -> KPIRow:
    d = state.data
    attempts = max(1, sum(1 for w in d.all_adws if w in ATTEMPT_WORKFLOWS))
    gates = d.gate_report.gates if d.gate_report else []
    return KPIRow(
        adw_id=d.adw_id, date=utcnow()[:10], domain=d.domain, issue_number=d.issue_number or "",
        issue_class=d.issue_class or "", attempts=attempts, plan_size=plan_size,
        added=diff.get("added", 0), removed=diff.get("removed", 0), files=diff.get("files", 0),
        cost_usd=round(d.usage.cost_usd, 4), gates_passed=sum(g.status == "passed" for g in gates),
        gates_total=len(gates), shipped=shipped, created=d.created, updated=utcnow(),
    )


def upsert(row: KPIRow) -> list[KPIRow]:
    rows = [r for r in load_rows() if r.adw_id != row.adw_id] + [row]
    path = _rows_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(r.model_dump_json() + "\n" for r in rows))
    render(rows)
    return rows


def summary(rows: list[KPIRow]) -> dict[str, float | int]:
    current = 0
    for r in reversed(rows):
        if r.attempts > STREAK_MAX_ATTEMPTS:
            break
        current += 1
    longest = run = 0
    for r in rows:
        run = run + 1 if r.attempts <= STREAK_MAX_ATTEMPTS else 0
        longest = max(longest, run)
    diffs = [r.added + r.removed for r in rows]
    gates_total = sum(r.gates_total for r in rows)
    return {
        "runs": len(rows),
        "current_streak": current,
        "longest_streak": longest,
        "total_plan_size": sum(r.plan_size for r in rows),
        "largest_plan_size": max((r.plan_size for r in rows), default=0),
        "total_diff_size": sum(diffs),
        "largest_diff_size": max(diffs, default=0),
        "average_presence": round(sum(r.attempts for r in rows) / len(rows), 2) if rows else 0.0,
        "total_cost_usd": round(sum(r.cost_usd for r in rows), 4),
        "gate_pass_rate": round(sum(r.gates_passed for r in rows) / gates_total, 3) if gates_total else 0.0,
        "shipped": sum(r.shipped for r in rows),
    }


def render(rows: list[KPIRow]) -> None:
    s = summary(rows)
    now = utcnow()
    lines = [
        "# Agentic KPIs",
        "",
        "Generated by `adws/adw_modules/kpis.py` from `agent/kpis.jsonl`. Do not edit by hand.",
        "",
        "## Agentic KPIs",
        "",
        "| Metric | Value | Last Updated |",
        "|---|---|---|",
    ]
    lines += [f"| {k.replace('_', ' ').title()} | {v} | {now} |" for k, v in s.items()]
    lines += [
        "",
        "## ADW KPIs",
        "",
        "| Date | ADW ID | Domain | Issue | Class | Attempts | Plan Size | Diff (+/-/files) | Cost USD | Gates | Shipped |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    lines += [
        f"| {r.date} | {r.adw_id} | {r.domain} | {r.issue_number} | {r.issue_class} | {r.attempts} | "
        f"{r.plan_size} | {r.added}/{r.removed}/{r.files} | {r.cost_usd:.4f} | {r.gates_passed}/{r.gates_total} | "
        f"{'yes' if r.shipped else 'no'} |"
        for r in rows
    ]
    (agent_dir() / "agentic_kpis.md").write_text("\n".join(lines) + "\n")


def as_json() -> str:
    rows = load_rows()
    return json.dumps({"summary": summary(rows), "rows": [r.model_dump() for r in rows]}, indent=2)
